// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {main} from '../models';

export function AddCustomAction(arg1:config.Action):Promise<config.Action>;

export function ConnectTwitch():Promise<void>;

export function DeleteAction(arg1:string):Promise<void>;

export function DeleteAllRewards():Promise<void>;

export function DisconnectTwitch():Promise<void>;

export function GetActions():Promise<Array<config.Action>>;

export function GetConfig():Promise<config.Config>;

export function GetCooldownRemaining(arg1:string):Promise<number>;

export function GetDebugLogPath():Promise<string>;

export function GetGlobalEnable():Promise<boolean>;

export function GetLanguage():Promise<string>;

export function GetLockedKeys():Promise<Array<string>>;

export function GetTarkovConfigPath():Promise<string>;

export function GetTwitchChannel():Promise<string>;

export function ImportTarkovKeybinds():Promise<number>;

export function IsTwitchConnected():Promise<boolean>;

export function SetGlobalEnable(arg1:boolean):Promise<void>;

export function SetLanguage(arg1:string):Promise<void>;

export function SetTargetWindow(arg1:string):Promise<void>;

export function SetTarkovConfigPath(arg1:string):Promise<void>;

export function StartTwitchAuth():Promise<main.DeviceAuthInfo>;

export function SyncRewards():Promise<void>;

export function ToggleAction(arg1:string,arg2:boolean):Promise<void>;

export function UpdateAction(arg1:config.Action):Promise<void>;
