// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCustomAction(arg1) {
  return window['go']['main']['App']['AddCustomAction'](arg1);
}

export function ConnectTwitch() {
  return window['go']['main']['App']['ConnectTwitch']();
}

export function DeleteAction(arg1) {
  return window['go']['main']['App']['DeleteAction'](arg1);
}

export function DeleteAllRewards() {
  return window['go']['main']['App']['DeleteAllRewards']();
}

export function DisconnectTwitch() {
  return window['go']['main']['App']['DisconnectTwitch']();
}

export function GetActions() {
  return window['go']['main']['App']['GetActions']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetCooldownRemaining(arg1) {
  return window['go']['main']['App']['GetCooldownRemaining'](arg1);
}

export function GetDebugLogPath() {
  return window['go']['main']['App']['GetDebugLogPath']();
}

export function GetGlobalEnable() {
  return window['go']['main']['App']['GetGlobalEnable']();
}

export function GetLanguage() {
  return window['go']['main']['App']['GetLanguage']();
}

export function GetLockedKeys() {
  return window['go']['main']['App']['GetLockedKeys']();
}

export function GetTarkovConfigPath() {
  return window['go']['main']['App']['GetTarkovConfigPath']();
}

export function GetTwitchChannel() {
  return window['go']['main']['App']['GetTwitchChannel']();
}

export function ImportTarkovKeybinds() {
  return window['go']['main']['App']['ImportTarkovKeybinds']();
}

export function IsTwitchConnected() {
  return window['go']['main']['App']['IsTwitchConnected']();
}

export function SetGlobalEnable(arg1) {
  return window['go']['main']['App']['SetGlobalEnable'](arg1);
}

export function SetLanguage(arg1) {
  return window['go']['main']['App']['SetLanguage'](arg1);
}

export function SetTargetWindow(arg1) {
  return window['go']['main']['App']['SetTargetWindow'](arg1);
}

export function SetTarkovConfigPath(arg1) {
  return window['go']['main']['App']['SetTarkovConfigPath'](arg1);
}

export function StartTwitchAuth() {
  return window['go']['main']['App']['StartTwitchAuth']();
}

export function SyncRewards() {
  return window['go']['main']['App']['SyncRewards']();
}

export function ToggleAction(arg1, arg2) {
  return window['go']['main']['App']['ToggleAction'](arg1, arg2);
}

export function UpdateAction(arg1) {
  return window['go']['main']['App']['UpdateAction'](arg1);
}
